### ISSUE TITLE
Put binaries into github releases?

### ISSUE THREAD

**Issue by drnic** [pivotal-golang/s3cli#15]
I only just learned about s3cli from recent release notes of bosh-cli. The readme infers its primarily a CLI. Perhaps its handy for each github release to include the prebuilt versions from CI - which are a little easier for 3rd party CI systems to discover and download?

**Comment by ljfranklin** [comment]
@drnic I'm curious about what use case you would have for consuming the s3cli. We don't really document that it exists because users shouldn't need to know that it exists :) It's more of an implementation detail of the Director / Agent.

That said, if you need to download and upload to s3-compatible blobstores with minimal configuration, this CLI might be useful.

**Comment by drnic** [comment]
I've been using awscli for S3 but then needed other clis to support gcs & Azure. If s3cli is going to be the communal code that bosh-cli is going to use to accsss diff blobstores then I thought I'd give it a try in lieu of awscli.
This assumption is all based on the bosh-cli release notes when it was mentioned that this repo existed with regards to GCS support.
I'm happy to help with docs/debugging/feedback directly for s3cli as I use it. The world needs more golang & cli multi-cloud tools. 






On Fri, Oct 21, 2016 at 7:48 AM +1000, "Lyle Franklin" <notifications@github.com> wrote:












@drnic I'm curious about what use case you would have for consuming the s3cli. We don't really document that it exists because users shouldn't need to know that it exists :) It's more of an implementation detail of the Director / Agent.



That said, if you need to download and upload to s3-compatible blobstores with minimal configuration, this CLI might be useful.

**Comment by ljfranklin** [comment]
> I'm happy to help with docs/debugging/feedback directly for s3cli as I use it.

Great, feel free to open issues and PRs. The docs are pretty lacking as the only consumers so far are the BOSH team, so your-milage-may-vary...

I added a link to the S3 bucket containing binaries to the README: 6d3927fa3fdb2e52a5014cf5a92d5dbdf84f5565. You should be able to grab the latest via a regex with the Concourse S3 resource or similar. Optimistically closing this out, but feel free to re-open if the S3 bucket doesn't meet your use case.

**Comment by drnic** [comment]
Thx






On Wed, Nov 2, 2016 at 7:26 AM +1000, "Lyle Franklin" <notifications@github.com> wrote:












Closed #15.
