### ISSUE TITLE
Cannot install the binary

### ISSUE THREAD

**Issue by vmarkovtsev** [pivotal-golang/s3cli#31]
Sorry for filing yet another "does not install" report, but it's really the case. The README says that the installation command is `go get ...` however it is officially deprecated and doesn't work:
```
$ go get github.com/cloudfoundry/bosh-s3cli
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

`go install` doesn't work for me either:

```
$ go install github.com/cloudfoundry/bosh-s3cli@latest
go: downloading github.com/cloudfoundry/bosh-s3cli v0.0.206
go: github.com/cloudfoundry/bosh-s3cli@latest (in github.com/cloudfoundry/bosh-s3cli@v0.0.206):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

I am using `go version go1.20.3 linux/amd64`.

How can I install the app rather than downgrading Go?

**Comment by vmarkovtsev** [comment]
P.S. `https://bosh-cpi.ci.cf-app.com/pipelines/s3cli` doesn't open and `https://s3cli-artifacts.s3.amazonaws.com/` is NoSuchBucket.

**Comment by ramonskie** [comment]
the main reason is because of the redirect we have in the go.mod which just reverts the aws-sdk-go.
this was done due to some incompatibility and a long lasting bug

i will see if the that bug is solved upstream in the meantime.
but do know that we do not support a standalone cli outside our bosh ecosystem.

**Comment by ramonskie** [comment]
i removed the redirect in https://github.com/cloudfoundry/bosh-s3cli/commit/233e88ed6f60cf7fb914d020898dcdc3cf97c968
so you should be able to use `go install` now
