### ISSUE TITLE
Support server-side encryption options

### ISSUE THREAD

**Issue by jmcarp** [pivotal-golang/s3cli#5]
It would be useful if s3cli could be configured to use server-side encryption, pulling options like `ServerSideEncryption`, `SSECustomerAlgorithm`, etc. from the config file and passing them to `PutObject`. I'm interested in this feature for use with bosh (https://github.com/cloudfoundry/bosh/pull/1278). If you all would be open to it, I'd be happy to submit a pull request.

**Comment by cppforlife** [comment]
@jmcarp i think it makes sense as long as we make it work optionally. s3cli also works for s3 compatible blobstores and gcp's blobstore (https://main.bosh-ci.cf-app.com/pipelines/s3cli).

**Comment by cppforlife** [comment]
tricky part is probably making sure that we expose configuration properties for this in the [Director](http://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=256.2#p=blobstore) and the [AWS CPI](http://bosh.io/jobs/aws_cpi?source=github.com/cloudfoundry-incubator/bosh-aws-cpi-release&version=52#p=agent.blobstore).
